### ISSUE TITLE
serverless-lift error since using serverless V4

### ISSUE THREAD

**Issue by richard-stafflink** [serverless/plugins#429]
serverless-lift: "version": "1.28.1"

When upgrading to serverless v4, I get the error: `(0 , import_logger.getUtils)(...).log is not a function`

```
(0 , import_logger.getUtils)(...).log is not a function
TypeError: (0 , import_logger.getUtils)(...).log is not a function
    at StaticWebsite.uploadWebsite (/codebuild/output/src3717290172/src/github.com/***-pty-ltd/sauron/web/node_modules/serverless-lift/dist/src/constructs/aws/abstracts/StaticWebsiteAbstract.js:198:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async StaticWebsite.postDeploy (/codebuild/output/src3717290172/src/github.com/***-pty-ltd/sauron/web/node_modules/serverless-lift/dist/src/constructs/aws/abstracts/StaticWebsiteAbstract.js:160:5)
    at async _LiftPlugin.postDeploy (/codebuild/output/src3717290172/src/github.com/***-pty-ltd/sauron/web/node_modules/serverless-lift/dist/src/plugin.js:350:9)
    at async PluginManager.runHooks (file:///root/.serverless/releases/4.0.23/package/dist/sf-core.js:668:10297)
    at async PluginManager.invoke (file:///root/.serverless/releases/4.0.23/package/dist/sf-core.js:668:11106)
    at async PluginManager.run (file:///root/.serverless/releases/4.0.23/package/dist/sf-core.js:668:11786)
    at async Serverless.run (file:///root/.serverless/releases/4.0.23/package/dist/sf-core.js:709:10075)
    at async runFramework (file:///root/.serverless/releases/4.0.23/package/dist/sf-core.js:988:3010)
    at async route (file:///root/.serverless/releases/4.0.23/package/dist/sf-core.js:991:3356)
    at async Object.run2 [as run] (file:///root/.serverless/releases/4.0.23/package/dist/sf-core.js:991:5252)
    at async Object.handler (file:///root/.serverless/releases/4.0.23/package/dist/sf-core.js:991:8193)
```

**Comment by eahefnawy** [comment]
Thanks for reporting that @richard-stafflink ... We're working on fixing this 👌

**Comment by richard-stafflink** [comment]
@eahefnawy @Mmarzex why was this issue closed without any explanation?

**Comment by Mmarzex** [comment]
Sorry @richard-stafflink we published a fix for this and it auto closed this issue. There is a new version available if you run `serverless update` this issue should be resolved.

**Comment by richard-stafflink** [comment]
Super! thanks @Mmarzex
